before_script: chmod 0777 ./node_modules/.bin/mocha
language: node_js
node_js:
  - "6"
  - "6.1"

dist: trusty
sudo: required

addons:
  sonarqube:
    token:
      secure: "bcf41583087483f18d4d4ef85b31ad2e5ce4ffcc"
jdk:
  - oraclejdk8
script:
  - sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'
