before_script: chmod 0777 ./node_modules/.bin/mocha
language: node_js
node_js:
  - "6"
  - "6.1"

dist: trusty
sudo: required

addons:
  sonarqube:
    token:
      secure: "your_token_encrypted_with_travis_encrypt_tool"
jdk:
  - oraclejdk8
script:
  - sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'
